//====================================================================================================
// Base code generated with Velocity: SL Gen (Build 2.4.5044.27855)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by MICAE_VI at BU-VILCH on 09/08/2014 17:33:15 
//====================================================================================================

using ViHISSrv.Business;
using ViHISSrv.Entities;
using ViHISSrv.Services.Contracts;
using log4net;
using System;
using System.Data;
using System.ServiceModel;

namespace ViHISSrv.Services
{
    [ServiceBehavior(InstanceContextMode = InstanceContextMode.PerCall, ConcurrencyMode = ConcurrencyMode.Multiple)]

    public class LH_DangKyLichHenService : ILH_DangKyLichHenService
    {
        public int DagKyLichHen_Insert(LH_DangKyLichHen obj)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.DagKyLichHen_Insert(obj);
        }

        public int XacNhanLichHen(int DangKyLichHen_Id, int NguoiXacNhan_Id)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.XacNhanLichHen(DangKyLichHen_Id, NguoiXacNhan_Id);
        }
        public int UpdateMaLichHen(int DangKyLichHen_Id, DateTime NgayKham)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.UpdateMaLichHen(DangKyLichHen_Id, NgayKham);
        }
        public int HuyHen(int DangKyLichHen_Id, int NguoiHuy_Id)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.HuyHen(DangKyLichHen_Id, NguoiHuy_Id);
        }

        public int DagKyLichHen_Update(LH_DangKyLichHen obj)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.DagKyLichHen_Update(obj);
        }

        public DataTable GetLichHen_By_UserId_TuNgay_DenNgay(string SDT,string Email, DateTime TuNgay, DateTime DenNgay, int PageNum, int PageSize)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.GetLichHen_By_UserId_TuNgay_DenNgay(SDT,Email ,TuNgay,DenNgay,PageNum,PageSize);
        }

        public DataTable GetLichHen_By_DangKyLichHen_Id(int DangKyLichHen_Id)
        {   
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.GetLichHen_By_DangKyLichHen_Id(DangKyLichHen_Id);
        }

        public DataTable GetLichHen_By_UserId_TrangThai_TuNgay_DenNgay_HoTen_SDT(/*Int32 ChuyenKhoa_Id,*/int UserId, DateTime TuNgay, DateTime DenNgay, int TrangThai, string TenBenhNhan, string SDT)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.GetLichHen_By_UserId_TrangThai_TuNgay_DenNgay_HoTen_SDT(/* ChuyenKhoa_Id,*/UserId, TuNgay, DenNgay, TrangThai,TenBenhNhan,SDT);
        }

        public DataTable GetLichHen_By_SDT(string SDT)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.GetLichHen_By_SDT(SDT);
        }

        public DataTable Search_LichHen(DateTime TuNgay, DateTime DenNgay, int TrangThai, string MaLichHen, string HoTen, int ChuyenKhoa_Id, int BacSi_Id, int PageNum, int PageSize)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.Search_LichHen(TuNgay, DenNgay, TrangThai, MaLichHen, HoTen, ChuyenKhoa_Id, BacSi_Id, PageNum, PageSize);
        }

        public DataTable Export_DSBenhNhan(DateTime TuNgay, DateTime DenNgay, int TrangThai, string MaLichHen, string HoTen, int ChuyenKhoa_Id, int BacSi_Id)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.Export_DSBenhNhan(TuNgay, DenNgay, TrangThai, MaLichHen, HoTen, ChuyenKhoa_Id, BacSi_Id);
        }

        public DataTable GetLichHen_By_MaLichHen(string MaLichHen)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.GetLichHen_By_MaLichHen(MaLichHen);
        }

        public DataTable DanhSachBenhNhanHenTrongNgay()
        {

            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.DanhSachBenhNhanHenTrongNgay();
        }

        public int HIS_DT_KhamBenh_Update_TrangThaiLichHen(int TrangThai_Id, int HIS_KhamBenh_Id)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.HIS_DT_KhamBenh_Update_TrangThaiLichHen(TrangThai_Id, HIS_KhamBenh_Id);
        }

        public DataTable CheckDatLich(DateTime TGBD, DateTime TGKT, DateTime NgayHen, int ChuyenKhoa_Id,int DangKyLichHen_Id)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.CheckDatLich(TGBD, TGKT, NgayHen, ChuyenKhoa_Id, DangKyLichHen_Id);
        }

        //public DataTable Check_GioDatLichHen(DateTime NgayHen, DateTime ThoiGianBatDau, DateTime ThoiGianKetThuc, int ChuyenKhoa_Id)
        //{
        //    LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
        //    return objDKLH.DanhSachBenhNhanHenTrongNgay();
        //}
        public int Update_SMSMDaGui(Int32 KhamBenh_Id)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.Update_SMSMDaGui(KhamBenh_Id);
        }

        public DataTable Check_DaGuiSMS(string strKhamBenh_Id)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.Check_DaGuiSMS(strKhamBenh_Id);
        }

        public int Update_LH_SMSMDaGui(int DangKyLichHen_Id)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.Update_LH_SMSMDaGui(DangKyLichHen_Id);
        }

        public DataTable Check_LH_DaGuiSMS(int DangKyLichHen_Id)
        {
            LH_DangKyLichHenComponent objDKLH = new LH_DangKyLichHenComponent();
            return objDKLH.Check_LH_DaGuiSMS(DangKyLichHen_Id);
        }
    }
}
