//====================================================================================================
// Base code generated with Velocity: SL Gen (Build 2.4.5044.27855)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by MICAE_VI at BU-VILCH on 09/08/2014 17:33:15 
//====================================================================================================

using ViHISSrv.Business;
using ViHISSrv.Entities;
using ViHISSrv.Services.Contracts;
using log4net;
using System;
using System.Data;
using System.ServiceModel;

namespace ViHISSrv.Services
{
    [ServiceBehavior(InstanceContextMode = InstanceContextMode.PerCall, ConcurrencyMode = ConcurrencyMode.Multiple)]

    public class ViCareService : IViCareService
    {
    
        #region Get info
        public string GetInfoBy_MabenhNhan(string MaBenhNhan)
        {
            int DangKyLichHen_Id = Int32.MinValue;
            ViCareComponent objc = new ViCareComponent();
            DataTable dt1 = objc.VC_Get_by_MaBenhNhan(MaBenhNhan);
            if (dt1.Rows[0]["Ref_DangKyLichHen_Id"] != null)
                DangKyLichHen_Id = Convert.ToInt32(dt1.Rows[0]["Ref_DangKyLichHen_Id"]);
            var dt2 = objc.LH_GetByKey(DangKyLichHen_Id);
            return dt2;
        }
        #endregion

        #region DangKyHenKB
        //DangKyHenKB_Insert
        public int LH_Insert(DangKyHenKBModel obj)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.LH_Insert(obj);
        }
        //DangKyHenKB_Update
        public int LH_Update(DangKyHenKBModel obj)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.LH_Update(obj);
        }
        //GetByKey
        public string LH_GetByKey(int DangKyLichHen_Id)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.LH_GetByKey(DangKyLichHen_Id);
        }
        //LH_GetBy_MaLichHen
        public string LH_GetBy_MaLichHen(string MaLichHen)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.LH_GetBy_MaLichHen(MaLichHen);
        }
        //DangKyHenKB_UpdateRandomMaLichHen
        public Int32 LH_UpdateRandomMaLichHen(int DangKyLichHen_Id)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.LH_UpdateRandomMaLichHen(DangKyLichHen_Id);
        }
        //GetByKey
        public string LH_Notification()
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.LH_Notification();
        }
        //TraCuuLichKham
        public string LH_TraCuu(string SoDienThoai)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.LH_TraCuu(SoDienThoai);
        }
        //HuyLichHen
        public int LH_Huy(int DangKyLichHen_Id,int NguoiHuy_Id)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.LH_Huy(DangKyLichHen_Id, NguoiHuy_Id);
        }
        #endregion

        #region ViCare
        //QMS_GetByCondition
        public string VC_Get_ThongTinSinhHieu(int DangKy_Id)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.VC_Get_ThongTinSinhHieu(DangKy_Id);
        }
        //VC_His_KhamBenh
        public DataSet VC_His_KhamBenh(int BenhNhan_Id)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.VC_His_KhamBenh (BenhNhan_Id);
        }
        //VC_His_CLS
        public string VC_His_CLS(int BenhNhan_Id)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.VC_His_CLS(BenhNhan_Id);
        }
        //VC_His_PTTT
        public string VC_His_PTTT(int BenhNhan_Id)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.VC_His_PTTT(BenhNhan_Id);
        }
        #endregion

        #region QMS
        //QMS_GetByCondition
        public string QMS_GetByCondition(string Type, int PhongBanID, int IntPara_0)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.QMS_GetByCondition(Type, PhongBanID, IntPara_0);
        }
        //QMS_Notification
        public string QMS_Notification(int BenhNhan_Id, string Type, int PhongBanID, int IntPara_0, int IntPara_1)
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.QMS_Notification(BenhNhan_Id, Type, PhongBanID, IntPara_0, IntPara_1);
        }
        #endregion

        #region Others
        public string Mas_BenhNhan_GetAll()
        {
            ViCareComponent objc = new ViCareComponent();
            return objc.Mas_BenhNhan_GetAll();
        }
        #endregion

    }
}
