//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5044.27856)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by ThienLoi at KHANHND-LAPTOP on 08/28/2014 11:03:35 
//====================================================================================================

using log4net;
using Microsoft.Practices.EnterpriseLibrary.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Reflection;
using ViHISSrv.Entities;
namespace ViHISSrv.Data
{

    public partial class ViCareDAC : DataAccessComponent
    {

        private string _ProcedureName = "usp_ViCare_DangKyHenKB";
        private string _ProcedureName_QMS = "usp_ViCare_QMS_Show";
        #region DangKyHenKB
        //Insert
        public Int32 DangKyHenKB_Insert(DangKyHenKBModel obj)
        {
            Int32 iResult = Int32.MinValue;
            try
            {
                Database db = DatabaseFactory.CreateDatabase(ConnectionDefine.HIS_LICHHEN);
                using (DbCommand cmd = db.GetStoredProcCommand(_ProcedureName))
                {
                    db.AddInParameter(cmd, "@Action", DbType.String, "DangKyHenKB_Insert");
                    db.AddOutParameter(cmd, "@DangKyLichHen_Id", DbType.Int32, obj.DangKyLichHen_Id);
                    db.AddInParameter(cmd, "@TenBenhNhan", DbType.String, obj.TenBenhNhan);
                    db.AddInParameter(cmd, "@NgaySinh", DbType.DateTime, obj.NgaySinh);
                    db.AddInParameter(cmd, "@GioiTinh", DbType.String, obj.GioiTinh);
                    db.AddInParameter(cmd, "@SoDienThoai", DbType.String, obj.SoDienThoai);
                    db.AddInParameter(cmd, "@Email", DbType.String, obj.Email);
                    db.AddInParameter(cmd, "@NgayHen", DbType.Date, obj.NgayHen);
                    db.AddInParameter(cmd, "@ChuyenKhoa_Id", DbType.Int32, obj.ChuyenKhoa_Id);
                    db.AddInParameter(cmd, "@ThoiGianBatDau", DbType.Time, obj.ThoiGianBatDau);
                    db.AddInParameter(cmd, "@ThoiGianKetThuc", DbType.Time, obj.@ThoiGianKetThuc);
                    db.AddInParameter(cmd, "@CreateBy_Id", DbType.Int32, obj.CreateBy_Id);

                    db.ExecuteNonQuery(cmd);
                    iResult = Convert.ToInt32(cmd.Parameters["@DangKyLichHen_Id"].Value);

                    return iResult;
                }
            }
            catch (Exception ex)
            {
                return -2;
            };
        }
        //Update
        public int DangKyHenKB_Update(DangKyHenKBModel mol)
        {
            Int32 iResult = Int32.MinValue;
            try
            {
                Database db = DatabaseFactory.CreateDatabase(ConnectionDefine.HIS_LICHHEN);
                using (DbCommand cm = db.GetStoredProcCommand(_ProcedureName))
                {
                    db.AddInParameter(cm, "@AcTion", DbType.String, "DangKyHenKB_Update");
                    db.AddInParameter(cm, "@DangKyLichHen_Id", DbType.Int32, mol.DangKyLichHen_Id);
                    db.AddInParameter(cm, "@TenBenhNhan", DbType.String, mol.TenBenhNhan);
                    db.AddInParameter(cm, "@NgaySinh", DbType.Date, mol.NgaySinh);
                    db.AddInParameter(cm, "@GioiTinh", DbType.String, mol.GioiTinh);
                    db.AddInParameter(cm, "@SoDienThoai", DbType.String, mol.SoDienThoai);
                    db.AddInParameter(cm, "@Email", DbType.String, mol.Email);
                    db.AddInParameter(cm, "@NgayHen", DbType.Boolean, mol.NgayHen);
                    db.AddInParameter(cm, "@ChuyenKhoa_Id", DbType.Boolean, mol.ChuyenKhoa_Id);
                    db.AddInParameter(cm, "@ThoiGianBatDau", DbType.Time, mol.ThoiGianBatDau);
                    db.AddInParameter(cm, "@ThoiGianKetThuc", DbType.Time, mol.ThoiGianKetThuc);
                    db.AddInParameter(cm, "@UpdateBy_Id", DbType.Int32, mol.UpdateBy_Id);

                    iResult = db.ExecuteNonQuery(cm);

                    return iResult;
                }
            }
            catch (Exception ex)
            {
                return -2;
            }
        }
        //GetByKey
        public DataTable GetByKey(int DangKyLichHen_Id)
        {
            DataTable dt = new DataTable();
            try
            {
                Database db = DatabaseFactory.CreateDatabase(ConnectionDefine.HIS_LICHHEN);
                using (DbCommand cmd = db.GetStoredProcCommand(_ProcedureName))
                {
                    db.AddInParameter(cmd, "@Action", DbType.String, "GetByKey");
                    db.AddInParameter(cmd, "@DangKyLichHen_Id", DbType.Int32, DangKyLichHen_Id);
                    DataSet ds = new DataSet();
                    ds = db.ExecuteDataSet(cmd);
                    if (ds != null && ds.Tables.Count > 0)
                    {
                        dt = ds.Tables[0];
                    }
                }
            }
            catch (Exception ex)
            {
                return null;
            }
            return dt;
        }
        //Update mã lịch hẹn
        public int DangKyHenKB_UpdateRandomMaLichHen(int DangKyLichHen_Id)
        {
            Int32 iResult = Int32.MinValue;
            try
            {
                Database db = DatabaseFactory.CreateDatabase(ConnectionDefine.HIS_LICHHEN);
                using (DbCommand cm = db.GetStoredProcCommand(_ProcedureName))
                {
                    db.AddInParameter(cm, "@AcTion", DbType.String, "DangKyHenKB_UpdateRandomMaLichHen");
                    db.AddInParameter(cm, "@DangKyLichHen_Id", DbType.Int32, DangKyLichHen_Id);

                    iResult = db.ExecuteNonQuery(cm);
                    return iResult;
                }
            }
            catch (Exception ex)
            {
                return -2;
            }

        }
        #endregion

        #region QMS
        //QMS_GetByCondition
        public DataTable QMS_GetByCondition(string Type, int PhongBanID, int IntPara_0)
        {
            Database db = DatabaseFactory.CreateDatabase(ConnectionDefine.HIS_APP);
            DataTable dt = new DataTable();
            try
            {
                using (DbCommand cmd = db.GetStoredProcCommand(_ProcedureName_QMS))
                {
                    db.AddInParameter(cmd, "@Action", DbType.String, "QMS_GetByCondition");
                    db.AddInParameter(cmd, "@Type", DbType.String, Type);
                    db.AddInParameter(cmd, "@PhongBanID", DbType.Int32, PhongBanID);
                    db.AddInParameter(cmd, "@IntPara_0", DbType.Int32, IntPara_0);
                    DataSet ds = new DataSet();
                    ds = db.ExecuteDataSet(cmd);
                    if (ds != null && ds.Tables.Count > 0)
                    {
                        dt = ds.Tables[0];
                    }
                }
            }
            catch (Exception ex)
            {
                return null;
            }
            return dt;
        }
        //
        public DataTable QMS_Notification(int BenhNhan_Id)
        {
            Database db = DatabaseFactory.CreateDatabase(ConnectionDefine.HIS_APP);
            DataTable dt = new DataTable();
            try
            {
                using (DbCommand cmd = db.GetStoredProcCommand(_ProcedureName_QMS))
                {
                    db.AddInParameter(cmd, "@Action", DbType.String, "QMS_Notification");
                    db.AddInParameter(cmd, "@BenhNhan_Id", DbType.Int32, BenhNhan_Id);
                    DataSet ds = new DataSet();
                    ds = db.ExecuteDataSet(cmd);
                    if (ds != null && ds.Tables.Count > 0)
                    {
                        dt = ds.Tables[0];
                    }
                }
            }
            catch (Exception ex)
            {
                return null;
            }
            return dt;
        }
        #endregion

        #region Others
        public DataTable Mas_BenhNhan_GetAll()
        {
            Database db = DatabaseFactory.CreateDatabase(ConnectionDefine.HIS_APP);
            DataTable dt = new DataTable();
            try
            {
                using (DbCommand cmd = db.GetStoredProcCommand("usp_Mas_BenhNhan"))
                {
                    db.AddInParameter(cmd, "@Action", DbType.String, "GetAll");
                    DataSet ds = new DataSet();
                    ds = db.ExecuteDataSet(cmd);
                    if (ds != null && ds.Tables.Count > 0)
                    {
                        dt = ds.Tables[0];
                    }
                }
            }
            catch (Exception ex)
            {
                return null;
            }
            return dt;
        }
        #endregion
    }
}

