//====================================================================================================
// Base code generated with Velocity: SL Gen (Build 2.4.5044.27855)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by MICAE_VI at BU-VILCH on 09/08/2014 17:33:15 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.ServiceModel;
using ViHISSrv.Entities;
using System.ServiceModel.Web;

namespace ViHISSrv.Services.Contracts
{
    /// <summary>
    /// Service contract for TAIKHOANService.
    /// </summary>
    [ServiceContract]
    public interface IAlfrescoHelperService
    {

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        byte[] DownloadFileFromAlfrescoServer(string fileName);


    }
}
