//====================================================================================================
// Base code generated with Velocity: SL Gen (Build 2.4.5044.27855)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by MICAE_VI at BU-VILCH on 09/08/2014 17:33:15 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.ServiceModel;
using ViHISSrv.Entities;
using System.ServiceModel.Web;
using System.Data;

namespace ViHISSrv.Services.Contracts
{
    /// <summary>
    /// Service contract for ILichHenService.
    /// </summary>
    [ServiceContract]
    public interface ILH_DangKyLichHenService
    {
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 DagKyLichHen_Insert(LH_DangKyLichHen obj);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 DagKyLichHen_Update(LH_DangKyLichHen obj);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 XacNhanLichHen(Int32 DangKyLichHen_Id, Int32 NguoiXacNhan_Id);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 UpdateMaLichHen(Int32 DangKyLichHen_Id ,DateTime NgayKham);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 HuyHen(Int32 DangKyLichHen_Id, Int32 NguoiHuy_Id);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable GetLichHen_By_UserId_TuNgay_DenNgay(string SDT, string Email, DateTime TuNgay, DateTime DenNgay, int PageNum, int PageSize);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable GetLichHen_By_DangKyLichHen_Id( int DangKyLichHen_Id);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable GetLichHen_By_UserId_TrangThai_TuNgay_DenNgay_HoTen_SDT(/*Int32 ChuyenKhoa_Id,*/Int32 UserId, DateTime TuNgay, DateTime DenNgay, Int32 TrangThai,string TenBenhNhan,string SDT);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable GetLichHen_By_SDT(string SDT);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable Search_LichHen(DateTime TuNgay, DateTime DenNgay,int TrangThai, string MaLichHen, string HoTen, int ChuyenKhoa_Id, int BacSi_Id, int PageNum, int PageSize);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable Export_DSBenhNhan(DateTime TuNgay, DateTime DenNgay, int TrangThai, string MaLichHen, string HoTen, int ChuyenKhoa_Id, int BacSi_Id);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable GetLichHen_By_MaLichHen(string MaLichHen);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable DanhSachBenhNhanHenTrongNgay();

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 HIS_DT_KhamBenh_Update_TrangThaiLichHen(Int32 TrangThai_Id, Int32 HIS_KhamBenh_Id);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable CheckDatLich(DateTime TGBD, DateTime TGKT, DateTime NgayHen, int ChuyenKhoa_Id, int DangKyLichHen_Id);
        //[OperationContract]
        //[WebGet(ResponseFormat = WebMessageFormat.Json)]
        //DataTable Check_GioDatLichHen(DateTime NgayHen, DateTime ThoiGianBatDau, DateTime ThoiGianKetThuc, int ChuyenKhoa_Id);
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 Update_SMSMDaGui(Int32 KhamBenh_Id);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable Check_DaGuiSMS(string  strKhamBenh_Id);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 Update_LH_SMSMDaGui(Int32 DangKyLichHen_Id);

        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable Check_LH_DaGuiSMS(Int32 DangKyLichHen_Id);
    }
}
