//====================================================================================================
// Base code generated with Velocity: SL Gen (Build 2.4.5044.27855)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by MICAE_VI at BU-VILCH on 09/08/2014 17:33:15 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.ServiceModel;
using ViHISSrv.Entities;
using System.ServiceModel.Web;
using System.Data;

namespace ViHISSrv.Services.Contracts
{
    /// <summary>
    /// Service contract for ILichHenService.
    /// </summary>
    [ServiceContract]
    public interface IViCareService
    {
        #region DangKyHenKB
        //Insert
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 DangKyHenKB_Insert(DangKyHenKBModel obj);
        //Update
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 DangKyHenKB_Update(DangKyHenKBModel obj);
        //GetByKey
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable GetByKey( int DangKyLichHen_Id);
        //GetByKey
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 DangKyHenKB_UpdateRandomMaLichHen(int DangKyLichHen_Id);
        #endregion

        #region QMS
        //QMS_GetByCondition
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable QMS_GetByCondition(string Type, int PhongBanID, int IntPara_0);
        #endregion

        #region Others
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable Mas_BenhNhan_GetAll();
        #endregion

    }
}
