//====================================================================================================
// Base code generated with Velocity: SL Gen (Build 2.4.5044.27855)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by MICAE_VI at BU-VILCH on 09/08/2014 17:33:15 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.ServiceModel;
using ViHISSrv.Entities;
using System.ServiceModel.Web;
using System.Data;

namespace ViHISSrv.Services.Contracts
{
    /// <summary>
    /// Service contract for ILichHenService.
    /// </summary>
    [ServiceContract]
    public interface IViCareService
    {
        #region Get Info
        //GetByKey
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable GetInfoBy_MabenhNhan(string MaBenhNhan);
        #endregion

        #region DangKyHenKB
        //Insert
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 Insert(DangKyHenKBModel obj);
        //Update
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 Update(DangKyHenKBModel obj);
        //GetByKey
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable GetByKey( int DangKyLichHen_Id);
        //UpdateRandomMaLichHen
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 UpdateRandomMaLichHen(int DangKyLichHen_Id);
        //LichHen_Notification
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable LichHen_Notification();
        //LichHen_Notification
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable TraCuuLichHen();
        //HuyLichHen
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        Int32 HuyLichHen(Int32 DangKyLichHen_Id,Int32 NguoiHuy_Id);
        #endregion

        #region QMS
        //QMS_GetByCondition
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable QMS_GetByCondition(string Type, int PhongBanID, int IntPara_0);


        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable QMS_Notification(int BenhNhan_Id, string Type, int PhongBanID, int IntPara_0,int IntPara_1);
        #endregion

        #region Others
        [OperationContract]
        [WebGet(ResponseFormat = WebMessageFormat.Json)]
        DataTable Mas_BenhNhan_GetAll();
        #endregion

    }
}
